---

- name: Add apt signing key docker
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg

- name: Add to docker.list
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: 'deb [arch=amd64] http://download.docker.com/linux/ubuntu xenial stable'
    create: yes

- name: Update  apt packages
  become: true
  apt:
    update_cache: yes

- name: Install docker
  apt:
    name: docker-ce=17.03.2~ce-0~ubuntu-xenial
    update_cache: yes

- name: Create the docker group
  group:
    name: docker

- name: Add vagrant user to the docker group
  user:
    name: vagrant
    groups: docker
    append: yes

- name: Start docker
  systemd:
    name: docker
    state: started
    enabled: yes
