---
# tasks file for ansible-role-k8s

- include_tasks: kube.yml

# - debug:
#    var:  k8s_mode

- import_tasks: master.yml
  when: (k8s_mode is defined and  k8s_mode == 'master')

- import_tasks: worker.yml
  when: (k8s_mode is defined and  k8s_mode == 'worker')

- import_tasks: teardown.yml
  when: (k8s_mode is defined and  k8s_mode == 'teardown')

