---
# tasks file for ansible-role-k8s


- include_tasks: docker.yml

- include_tasks: kube.yml


- include_tasks: master.yml
  when: k8s_mode == 'master'

- include_tasks: worker.yml
  when: k8s_mode == 'worker'

- include_tasks: teardown.yml
  when: k8s_mode == 'teardown'
