---
- name: System bridge iptable setup
  sysctl:
       name: net.bridge.bridge-nf-call-iptables
       value: 1
       reload: yes

- name: Reset all kubeadm installed state
  command: kubeadm reset --cri-socket unix:///var/run/dockershim.sock -v1  --force
  ignore_errors: true

- name: Initialise Master node
  command: kubeadm init --apiserver-advertise-address=192.168.99.20 --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=cri
  register: kubeadm_output

- name: Create .kube directory
  become: no
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
  register: kube_dir

- name: Set fact for kubeadm join command
  set_fact:
    kubeadm_join_cmd: '{{ kubeadm_output.stdout_lines | last }}'

- name: Copy kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: '{{ kube_dir.path }}/config'
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Download a kube-flannel.yaml 
  get_url:
    url: https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
    dest: /home/vagrant/kube-flannel.yml

- name: Edit a kube-flannel.yaml iface enp0s8 
  lineinfile:
    path: /home/vagrant/kube-flannel.yml
    insertafter: '- --kube-subnet-mgr'
    line: '        - --iface=enp0s8'

- name: Deploy pod network to the cluster
  become: no
  command: kubectl apply -f /home/vagrant/kube-flannel.yml
