---
- name: Add KUBELET_KUBECONFIG_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_KUBECONFIG_ARGS=--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf"'

- name: Add KUBELET_SYSTEM_PODS_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_SYSTEM_PODS_ARGS=--pod-manifest-path=/etc/kubernetes/manifests --allow-privileged=true"'

- name: Add KUBELET_NETWORK_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_NETWORK_ARGS=--network-plugin=cni --cni-conf-dir=/etc/cni/net.d --cni-bin-dir=/opt/cni/bin"'

- name: Add KUBELET_AUTHZ_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_AUTHZ_ARGS=--authorization-mode=Webhook --client-ca-file=/etc/kubernetes/pki/ca.crt"'

- name: Add KUBELET_CADVISOR_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_CADVISOR_ARGS=--cadvisor-port=0"'

- name: Add KUBELET_CERTIFICATE_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_CERTIFICATE_ARGS=--rotate-certificates=true --cert-dir=/var/lib/kubelet/pki"'

- name: Add KUBELET_EXTRA_ARGS environment variable
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    line: 'Environment="KUBELET_EXTRA_ARGS=--node-ip={{ ansible_enp0s8.ipv4.address }}"'


#- name: Add KUBELET_CGROUP_DRIVER environment variable
#  lineinfile:
#    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
#    line: 'Environment="KUBELET_CGROUP_DRIVER=--cgroup-driver=cgroupfs"'

- name: Append $KUBELET_ARGS to ExecStart=
  lineinfile:
    path: /etc/systemd/system/kubelet.service.d/10-kubeadm.conf
    regexp: '^ExecStart=/usr/bin/kubelet'
    line: 'ExecStart=/usr/bin/kubelet $KUBELET_KUBECONFIG_ARGS $KUBELET_SYSTEM_PODS_ARGS $KUBELET_NETWORK_ARGS $KUBELET_DNS_ARGS $KUBELET_AUTHZ_ARGS $KUBELET_CADVISOR_ARGS $KUBELET_CGROUP_ARGS $KUBELET_CERTIFICATE_ARGS $KUBELET_EXTRA_ARGS'
  notify: restart kubelet

- name: System bridge iptable setup
  sysctl:
       name: net.bridge.bridge-nf-call-iptables
       value: 1
       reload: yes

- name: Reset all kubeadm installed state
  command: kubeadm reset --cri-socket unix:///var/run/dockershim.sock -v1  --force
  ignore_errors: true

- name: Initialise Master node
  command: kubeadm init --apiserver-advertise-address=192.168.99.20 --pod-network-cidr=10.244.0.0/16 --ignore-preflight-errors=cri
  register: kubeadm_output

- name: Create .kube directory
  become: no
  file:
    path: /home/vagrant/.kube
    state: directory
    owner: vagrant
    group: vagrant
  register: kube_dir

- name: Set fact for kubeadm join command
  set_fact:
    kubeadm_join_cmd: '{{ kubeadm_output.stdout_lines | last }}'

- name: Copy kube config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: '{{ kube_dir.path }}/config'
    remote_src: yes
    owner: vagrant
    group: vagrant

- name: Deploy pod network to the cluster
  become: no
  command: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml


